server:
  port: 8086

spring:
  application:
    name: batch-service
  datasource:
    url: jdbc:h2:mem:batchdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    job:
      enabled: false  # Disable job execution at startup
    jdbc:
      initialize-schema: always
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/